import { Header } from '@/components/ui/header';
import { jost } from '@/lib/next/fonts';
import { cx } from 'class-variance-authority';

import type { Metadata } from 'next';

import styles from './layout.module.css';

import '@unocss/reset/tailwind.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = React.PropsWithChildren;

const Layout = ({ children }: Props) => (
  <html lang="en">
    <body className={cx(styles.base, jost.className)}>
      <div className={styles.header}>
        <Header />
      </div>
      <main className={styles.main}>{children}</main>
    </body>
  </html>
);

export default Layout;
