import { jost } from '@/lib/next';

import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  // todo: set metadata
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = React.PropsWithChildren;

const RootLayout = ({ children }: Props) => (
  <html lang="en">
    <body className={jost.className}>{children}</body>
  </html>
);

export default RootLayout;
