import { Footer } from '@/components/ui/footer';
import { Header } from '@/components/ui/header';
import { jost } from '@/lib/next';


import type { Metadata } from 'next';

import styles from './layout.module.css';
import '@unocss/reset/tailwind.css';
import './globals.css';

export const metadata: Metadata = {
  // todo: set metadata
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = React.PropsWithChildren;

const Layout = ({ children }: Props) => (
  <html lang="en">
    <body className={jost.className}>
      <div className={styles.base}>
        <div className={styles.header}>
          <Header />
        </div>
        <main className={styles.main}>{children}</main>
        <div className={styles.footer}>
          <Footer />
        </div>
      </div>
    </body>
  </html>
);

export default Layout;
